### ISSUE TITLE
Пофиксить прощальное сообщение

### ISSUE THREAD

**Issue by wiltort** [proDreams/napkin_contest#2]
Если админ выкидывает чат-мембера то бот прощается с АДМИНОМ! и называет его предателем

**Comment by wiltort** [comment]
![изображение](https://github.com/proDreams/napkin_contest/assets/133680257/b34fbfeb-850b-43e8-8dd8-3572a3d32ef0)

**Comment by proDreams** [comment]
Точно, тут старая версия. У меня пофикшено. Залью вместе со своеё капчей
![image](https://github.com/proDreams/napkin_contest/assets/6825325/344dccba-4d89-41e2-a017-7fc9dd2e4a99)
